name: Verify hashs of the documents
on:
  workflow_dispatch:
    inputs:
      number_of_jobs:
        description: "Number of Jobs"
        required: true
        default: 20

jobs:
  generate-job-strategy-matrix:
    runs-on: ubuntu-latest
    outputs:
      job-strategy-matrix: ${{ steps.generate.outputs.job-strategy-matrix }}
    steps:
      - id: generate
        run: |
          arr=[`seq -s , $NUMBER_OF_JOBS | sed 's/,$//'`]
          echo "::set-output name=job-strategy-matrix::$arr"
        env:
          NUMBER_OF_JOBS: ${{ github.event.inputs.number_of_jobs }}
  job:
    needs: generate-job-strategy-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 3600 # 60 hour timeout
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-job-strategy-matrix.outputs.job-strategy-matrix) }}
      # max-parallel: 1 # Run jobs serially
      max-parallel: ${{ fromJson(github.event.inputs.number_of_jobs) }} # Run jobs in parallel
    steps:
      - run: echo "This is job number ${{ matrix.job }}"